<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="appsettings.Development.json">
      <LogicalName>HRM_API.Configuration.appsettings.Development.json</LogicalName>
    </EmbeddedResource>

    <EmbeddedResource Include="appsettings.json">
      <LogicalName>HRM_API.Configuration.appsettings.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
  </ItemGroup>

</Project>
